"""add fields to booking table: name, datetime, service_type

Revision ID: a0c5196fecb6
Revises: 01e357b26552
Create Date: 2026-06-18 21:10:40.144316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a0c5196fecb6'
down_revision: Union[str, Sequence[str], None] = '01e357b26552'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


status_enum = sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', name='statusenum')
def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    status_enum.create(op.get_bind(), checkfirst=True)

    op.add_column('booking', sa.Column('name', sa.String(length=255), nullable=False))
    op.add_column('booking', sa.Column('datetime', sa.DateTime(timezone=True), nullable=False))
    op.add_column('booking', sa.Column('service_type', sa.String(length=255), nullable=False))
    op.create_index(op.f('ix_booking_id'), 'booking', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_id'), table_name='booking')
    op.drop_column('booking', 'service_type')
    op.drop_column('booking', 'datetime')
    op.drop_column('booking', 'name')

    op.drop_column('booking', 'status')
    status_enum.drop(op.get_bind(), checkfirst=True)
    # ### end Alembic commands ###
