"""create table

Revision ID: bed49fa68b32
Revises: 
Create Date: 2026-06-21 14:04:11.449895

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bed49fa68b32'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('booking',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('datetime', sa.DateTime(timezone=True), nullable=False),
    sa.Column('service_type', sa.String(length=255), nullable=False),
    sa.Column('status', sa.Enum('pending', 'confirmed', 'failed', name='status_enum'), server_default='pending', nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_booking_id'), 'booking', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_booking_id'), table_name='booking')
    op.drop_table('booking')
    # ### end Alembic commands ###
